# Generated by Django 4.0.6 on 2022-07-28 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proprietario', '0003_remove_proprietario_carros'),
        ('carro', '0002_carro_proprietario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carro',
            name='proprietario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carros', to='proprietario.proprietario'),
        ),
    ]
