# Generated by Django 4.0.6 on 2022-07-28 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proprietario', '0004_proprietario_totalcarros'),
        ('carro', '0003_alter_carro_proprietario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carro',
            name='proprietario',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='carros', to='proprietario.proprietario'),
            preserve_default=False,
        ),
    ]
