# Generated by Django 4.0.6 on 2022-07-28 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proprietario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100)),
                ('protencialComprador', models.BooleanField(default=True)),
                ('carros', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='carro.carro')),
            ],
        ),
    ]
