# Generated by Django 4.0.6 on 2022-07-28 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proprietario', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proprietario',
            old_name='protencialComprador',
            new_name='potencialComprador',
        ),
    ]
