# Generated by Django 4.0.6 on 2022-07-28 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proprietario', '0002_rename_protencialcomprador_proprietario_potencialcomprador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proprietario',
            name='carros',
        ),
    ]
